### ISSUE TITLE
Error while running "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by albertodallolio** [erikwijmans/Pointnet2_PyTorch#107]
Hello, 
I am trying to do the setup for using PointNet++. My environment contains Python = 3.6.10, cuda=10.1 and pytorch=1.5.0. If I try running "pip install -r requirements.txt" I receive the following errors during the compiling:

`ERROR: Command errored out with exit status 1:
   command: /home/alberto/anaconda3/envs/pn2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ezjt_ypu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ezjt_ypu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-004bspdj
       cwd: /tmp/pip-req-build-ezjt_ypu/
  Complete output (169 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pointnet2_ops
  copying pointnet2_ops/__init__.py -> build/lib.linux-x86_64-3.6/pointnet2_ops
  copying pointnet2_ops/pointnet2_utils.py -> build/lib.linux-x86_64-3.6/pointnet2_ops
  copying pointnet2_ops/_version.py -> build/lib.linux-x86_64-3.6/pointnet2_ops
  copying pointnet2_ops/pointnet2_modules.py -> build/lib.linux-x86_64-3.6/pointnet2_ops
  running egg_info
  creating pointnet2_ops.egg-info
  writing pointnet2_ops.egg-info/PKG-INFO
  writing dependency_links to pointnet2_ops.egg-info/dependency_links.txt
  writing top-level names to pointnet2_ops.egg-info/top_level.txt
  writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  reading manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src
  creating build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/ball_query.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/cuda_utils.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/group_points.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/interpolate.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/sampling.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/utils.h -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/include
  creating build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/ball_query.cpp -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/ball_query_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/bindings.cpp -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/group_points.cpp -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/group_points_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/interpolate.cpp -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/interpolate_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/sampling.cpp -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  running build_ext
  building 'pointnet2_ops._ext' extension
  creating /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6
  creating /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops
  creating /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src
  creating /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
  Emitting ninja build file /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/9] c++ -MMD -MF /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o.d -pthread -B /home/alberto/anaconda3/envs/pn2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipointnet2_ops/_ext-src/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/TH -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/alberto/anaconda3/envs/pn2/include/python3.6m -c -c /tmp/pip-req-build-ezjt_ypu/pointnet2_ops/_ext-src/src/sampling.cpp -o /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  FAILED: /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o
  c++ -MMD -MF /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o.d -pthread -B /home/alberto/anaconda3/envs/pn2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipointnet2_ops/_ext-src/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/TH -I/home/alberto/anaconda3/envs/pn2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/alberto/anaconda3/envs/pn2/include/python3.6m -c -c /tmp/pip-req-build-ezjt_ypu/pointnet2_ops/_ext-src/src/sampling.cpp -o /tmp/pip-req-build-ezjt_ypu/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /tmp/pip-req-build-ezjt_ypu/pointnet2_ops/_ext-src/src/sampling.cpp:1:10: fatal error: sampling.h: File o directory non esistente
   #include "sampling.h"
            ^~~~~~~~~~~~
`

It does the same thing for all the other files to be compiled. Can you please help with that?

**Comment by erikwijmans** [comment]
Looks like pytorch 1.5 changed a fair amount of things for CUDA/CPP extensions.  I will update this repo when I have the time (not entirely sure when that will be).  For now, please use pytorch < 1.5
