### ISSUE TITLE
gcc error when install pointnet2_ops

### ISSUE THREAD

**Issue by chenghongkuan** [erikwijmans/Pointnet2_PyTorch#108]
as title
my python version is 3.6 
tourch 1.1.0 
CUDA Version 10.1.168
gcc 5.5.0
I have Google ， but find nothing useful
![image](https://user-images.githubusercontent.com/9548831/81265639-099c4b80-9076-11ea-9c27-6c85e927daa8.png)
![image](https://user-images.githubusercontent.com/9548831/81265701-1f117580-9076-11ea-9c08-e7be525960ee.png)

**Comment by erikwijmans** [comment]
`data_ptr` is the newer API, I believe it was introduced in pytorch 1.2, but it could have been pytorch 1.3.  Please update pytorch.  Note that this repo currently isn't compatible with 1.5 as there was changes to cpp extensions in 1.5.
