### ISSUE TITLE
Build of CUDA kernels on Colab

### ISSUE THREAD

**Issue by chodi150** [erikwijmans/Pointnet2_PyTorch#109]
Hello @erikwijmans ,
I experience problems with executing setup of pointnet2_ops_lib on google colab. I have downgraded pytorch to 1.2.0,  torchvision to 0.4.0. Gcc compiler is 6.5 and Cuda compiler is 10.1

There are many warnings and unluckily also error. I attach the logs. I'm a bit clueless already what might have gone wrong.

>   pointnet2_ops/_ext-src/src/sampling.cpp:83:5: note: in expansion of macro ‘AT_CHECK’
         AT_CHECK(false, "CPU not supported");
         ^
    In file included from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Device.h:5:0,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Allocator.h:6,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                     from pointnet2_ops/_ext-src/include/sampling.h:2,
                     from pointnet2_ops/_ext-src/src/sampling.cpp:1:
    /usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:314:13: note: declared here
     inline void deprecated_AT_CHECK() {}
                 ^~~~~~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Running setup.py install for pointnet2-ops ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-murshflr
Removed build tracker '/tmp/pip-req-tracker-jahrtnyl'
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-murshflr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-murshflr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ibjpg40s/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 888, in install
    cwd=self.unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-murshflr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-murshflr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ibjpg40s/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by erikwijmans** [comment]
Hi, can you try master?  I moved master from AT_CHECK to the newer AT_ASSERT.

**Comment by chodi150** [comment]
Everything works now. Thank you!
