### ISSUE TITLE
error using KITTI dataset on the segmentation part

### ISSUE THREAD

**Issue by NehilDanis** [erikwijmans/Pointnet2_PyTorch#112]
Hello,

in my project I am currently using the segmentation part. The aim is once the model is trained it will be used to assign feature vectors to the KITTI dataset. So I picked one just one of the files in KITTI velodyne dataset and prepared the data as [30, 4096, 4], I load the checkpoint from the trained model. But once the data reached to SAModule, the furthest point sampling algorithm gives me the following error;

> File "/home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/pointnet2_ops/pointnet2_modules.py", line 57, in forward
    if self.npoint is not None
  File "/home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/pointnet2_ops/pointnet2_utils.py", line 54, in forward
    out = _ext.furthest_point_sampling(xyz, npoint)
RuntimeError: false INTERNAL ASSERT FAILED at pointnet2_ops/_ext-src/src/sampling.cpp:83, please report a bug to PyTorch. CPU not supported (furthest_point_sampling at pointnet2_ops/_ext-src/src/sampling.cpp:83)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fc49b6c0193 in /home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: furthest_point_sampling(at::Tensor, int) + 0x4eb (0x7fc495afd89b in /home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/pointnet2_ops/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x2b842 (0x7fc495b0f842 in /home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/pointnet2_ops/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x2858a (0x7fc495b0c58a in /home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/pointnet2_ops/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x5578a66d96e4 in /home/nehil/Documents/environments/nehil/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x5578a66d9801 in /home/nehil/Documents/environments/nehil/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x4e8c (0x5578a67352bc in /home/nehil/Documents/environments/nehil/bin/python)
frame #7: _PyFunction_FastCallDict + 0x10b (0x5578a667750b in /home/nehil/Documents/environments/nehil/bin/python)
frame #8: THPFunction_apply(_object*, _object*) + 0xa7f (0x7fc4f91593ef in /home/nehil/Documents/environments/nehil/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: _PyMethodDef_RawFastCallKeywords + 0x1e0 (0x5578a66d9660 in /home/nehil/Documents/environments/nehil/bin/python)
frame #10: _PyCFunction_FastCallKeywords + 0x21 (0x5578a66d9801 in /home/nehil/Documents/environments/nehil/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x4e8c (0x5578a67352bc in /home/nehil/Documents/environments/nehil/bin/python)
frame #12: _PyFunction_FastCallDict + 0x10b (0x5578a667750b in /home/nehil/Documents/environments/nehil/bin/python)
frame #13: _PyObject_Call_Prepend + 0x63 (0x5578a668ec43 in /home/nehil/Documents/environments/nehil/bin/python)
frame #14: PyObject_Call + 0x6e (0x5578a668395e in /home/nehil/Documents/environments/nehil/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x1e20 (0x5578a6732250 in /home/nehil/Documents/environments/nehil/bin/python)
frame #16: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #17: _PyFunction_FastCallDict + 0x1d5 (0x5578a66775d5 in /home/nehil/Documents/environments/nehil/bin/python)
frame #18: _PyObject_Call_Prepend + 0x63 (0x5578a668ec43 in /home/nehil/Documents/environments/nehil/bin/python)
frame #19: <unknown function> + 0x17116a (0x5578a66d116a in /home/nehil/Documents/environments/nehil/bin/python)
frame #20: _PyObject_FastCallKeywords + 0x49b (0x5578a66d9d2b in /home/nehil/Documents/environments/nehil/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x4bf6 (0x5578a6735026 in /home/nehil/Documents/environments/nehil/bin/python)
frame #22: _PyFunction_FastCallDict + 0x10b (0x5578a667750b in /home/nehil/Documents/environments/nehil/bin/python)
frame #23: _PyObject_Call_Prepend + 0x63 (0x5578a668ec43 in /home/nehil/Documents/environments/nehil/bin/python)
frame #24: PyObject_Call + 0x6e (0x5578a668395e in /home/nehil/Documents/environments/nehil/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1e20 (0x5578a6732250 in /home/nehil/Documents/environments/nehil/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #27: _PyFunction_FastCallDict + 0x1d5 (0x5578a66775d5 in /home/nehil/Documents/environments/nehil/bin/python)
frame #28: _PyObject_Call_Prepend + 0x63 (0x5578a668ec43 in /home/nehil/Documents/environments/nehil/bin/python)
frame #29: <unknown function> + 0x17116a (0x5578a66d116a in /home/nehil/Documents/environments/nehil/bin/python)
frame #30: _PyObject_FastCallKeywords + 0x49b (0x5578a66d9d2b in /home/nehil/Documents/environments/nehil/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x4bf6 (0x5578a6735026 in /home/nehil/Documents/environments/nehil/bin/python)
frame #32: _PyFunction_FastCallKeywords + 0xfb (0x5578a66d879b in /home/nehil/Documents/environments/nehil/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x416 (0x5578a6730846 in /home/nehil/Documents/environments/nehil/bin/python)
frame #34: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0x387 (0x5578a66d8a27 in /home/nehil/Documents/environments/nehil/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x14ce (0x5578a67318fe in /home/nehil/Documents/environments/nehil/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #38: _PyFunction_FastCallKeywords + 0x387 (0x5578a66d8a27 in /home/nehil/Documents/environments/nehil/bin/python)
frame #39: _PyEval_EvalFrameDefault + 0x14ce (0x5578a67318fe in /home/nehil/Documents/environments/nehil/bin/python)
frame #40: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #41: _PyFunction_FastCallKeywords + 0x387 (0x5578a66d8a27 in /home/nehil/Documents/environments/nehil/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x14ce (0x5578a67318fe in /home/nehil/Documents/environments/nehil/bin/python)
frame #43: _PyEval_EvalCodeWithName + 0xbb9 (0x5578a6676db9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #44: _PyFunction_FastCallKeywords + 0x387 (0x5578a66d8a27 in /home/nehil/Documents/environments/nehil/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x416 (0x5578a6730846 in /home/nehil/Documents/environments/nehil/bin/python)
frame #46: _PyEval_EvalCodeWithName + 0x2f9 (0x5578a66764f9 in /home/nehil/Documents/environments/nehil/bin/python)
frame #47: PyEval_EvalCodeEx + 0x44 (0x5578a66773c4 in /home/nehil/Documents/environments/nehil/bin/python)
frame #48: PyEval_EvalCode + 0x1c (0x5578a66773ec in /home/nehil/Documents/environments/nehil/bin/python)
frame #49: <unknown function> + 0x22f874 (0x5578a678f874 in /home/nehil/Documents/environments/nehil/bin/python)
frame #50: PyRun_FileExFlags + 0xa1 (0x5578a6799b81 in /home/nehil/Documents/environments/nehil/bin/python)
frame #51: PyRun_SimpleFileExFlags + 0x1c3 (0x5578a6799d73 in /home/nehil/Documents/environments/nehil/bin/python)
frame #52: <unknown function> + 0x23ae5f (0x5578a679ae5f in /home/nehil/Documents/environments/nehil/bin/python)
frame #53: _Py_UnixMain + 0x3c (0x5578a679af7c in /home/nehil/Documents/environments/nehil/bin/python)
frame #54: __libc_start_main + 0xe7 (0x7fc4fe845b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #55: <unknown function> + 0x1e0122 (0x5578a6740122 in /home/nehil/Documents/environments/nehil/bin/python)

I actually put the points that I am sending to the forward function on cuda and they are float32. If you could shed some light, that would be perfect.

Thanks in advance,
Nehil

**Comment by saru-d2** [comment]
Hi @NehilDanis, do you remember how you fixed this?

**Comment by NehilDanis** [comment]
> Hi @NehilDanis, do you remember how you fixed this?

Hi, unfortunately I don't remember exactly. But I do remember that it was something trivial and I closed the issue directly. Have you solved it yet?

**Comment by saru-d2** [comment]
> > Hi @NehilDanis, do you remember how you fixed this?
> 
> Hi, unfortunately I don't remember exactly. But I do remember that it was something trivial and I closed the issue directly. Have you solved it yet?

yes I have, Thanks!
and in case anyone else is wondering what the issue was, I can not recall it at the moment

**Comment by SvyJ** [comment]
Now I have encountered the same problem, I would like to ask if you can recall an effective solution?
