### ISSUE TITLE
Where is etw_pytorch_utils?

### ISSUE THREAD

**Issue by chenerg** [erikwijmans/Pointnet2_PyTorch#114]
Seems it require  etw_pytorch_utils, but I'm not sure where to put  etw_pytorch_utils. And is there a way to install  etw_pytorch_utils as a module.

**Comment by erikwijmans** [comment]
That is an old repo of mine with some pytorch utils that are now almost entirely subsumed by libraries like pytorch-lightning and/or new features in pytorch proper.  That is is not needed for master in this repo.
