### ISSUE TITLE
Classification input data features

### ISSUE THREAD

**Issue by yangvnks** [erikwijmans/Pointnet2_PyTorch#123]
Hello,

I'm using a custom dataset containing 3D points to perform SSG classification. My input data has no additional features other than its coordinates xyz. While performing the validation sanity check I get the following error :
`RuntimeError: Given groups=1, weight of size 64 6 1 1, expected input[32, 3, 512, 64] to have 6 channels, but got 3 channels instead` which is thrown by [this line of code](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2_ops_lib/pointnet2_ops/pointnet2_modules.py#L66).
In the [PointnetSA module](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2_ops_lib/pointnet2_ops/pointnet2_modules.py#L112) the `use_xyz` block adds +3 to the first MLP element, so instead of expecting 3 point features it expects 6 input features even in the **first** set abstraction layer.  I understand that new features are created along the hierarchy but the first set abstraction layer should be able to work with just its three coordinates (correct me if I'm wrong!). 
Thanks for any help!

**Comment by erikwijmans** [comment]
The operations support `features=None` and having `[0]` as the first dimension in the MLP is valid.  The example model implementations aren't set up to support that however.  You will need to modify the initial MLP specs to expect that and/or add a field to the config (e.g. here: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/models/pointnet2_ssg_cls.py#L70)

**Comment by paulm423** [comment]
Hi @yangvnks 

I am also using data with no additionnal features, did you find an easy way to modify the code, so it does not raise an error?

Thanks

**Comment by yangvnks** [comment]
Hi @paulm423 ,

Fastest way I found was to modify [this line](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/models/pointnet2_ssg_cls.py#L70) with `mlp=[0, 64, 64, 128]`. This way when using `use_xyz` only the three coordinates are used.
Hope that helps.

**Comment by yimingli1998** [comment]
> Hi @paulm423 ,
> 
> Fastest way I found was to modify [this line](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/models/pointnet2_ssg_cls.py#L70) with `mlp=[0, 64, 64, 128]`. This way when using `use_xyz` only the three coordinates are used.
> Hope that helps.
Hello, @yangvnks,
I meet the same question and modify `mlp=[3, 64, 64, 128]` with `mlp=[0, 64, 64, 128]`, but it still doesn't work. Is there anything I missed? 
Thanks for your help!

**Comment by yimingli1998** [comment]
Hello, @yangvnks,
I meet the same question and modify mlp=[3, 64, 64, 128] with mlp=[0, 64, 64, 128], but it still doesn't work. Is there anything I missed?
Thanks for your help!

**Comment by AnselmC** [comment]
For others using the SSG segmentation task, you'll need to additionally remove the `+6` from [this line](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/acda965224f35854bc331cd5fe140393216b0a71/pointnet2/models/pointnet2_ssg_sem.py#L52).
