### ISSUE TITLE
some question about the implementation  orthogonal matrix

### ISSUE THREAD

**Issue by MaybeOjbk** [erikwijmans/Pointnet2_PyTorch#125]
your code 
![图片](https://user-images.githubusercontent.com/38483419/89382910-29ebad00-d72e-11ea-85c1-de8ba82353ae.png)

which means  || A(A.T- I ) ||   equals to  || I - AA.T || ?

**Comment by erikwijmans** [comment]
That parenthesis is in the wrong spot, the subtraction should be outside the bmm.  Where is that code from?  I don't think that is in master or any recent commit of this repo.

**Comment by MaybeOjbk** [comment]
I'm so sorry about the mistake , I got from [https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet.py](url) ,
