### ISSUE TITLE
how to change the number of input channels when just using the xyz info?

### ISSUE THREAD

**Issue by pengPeterpeng** [erikwijmans/Pointnet2_PyTorch#128]
hello! I am trying to use another dataset to train pointnet2. however, the new dataset just contains the xyz info of points(3 dim). and when I run the training file, the result shows 
"RuntimeError: Given groups=1, weight of size [64, 6, 1, 1], expected input[32, 3, 512, 64] to have 6 channels, but got 3 channels instead"
Thanks in advance!

**Comment by erikwijmans** [comment]
https://github.com/erikwijmans/Pointnet2_PyTorch/issues/123
