### ISSUE TITLE
Compatible with Pytorch3d ?

### ISSUE THREAD

**Issue by albertotono** [erikwijmans/Pointnet2_PyTorch#130]
Dear @erikwijmans , 

thanks for the great work, I was wondering if this code is compatible with Pytorch3d, with the `pointclouds structures`. 

Best Regards

**Comment by erikwijmans** [comment]
There isn't explicit support for pytorch3D.  The models expect point clouds to be (B, N, C) where `C = <x, y, z, features...>` so if pytorch3d can output point clouds as that, it'll work.
