### ISSUE TITLE
Pytorch 1.0.0 support issue

### ISSUE THREAD

**Issue by chickenbestlover** [erikwijmans/Pointnet2_PyTorch#14]
Hello, erikwijmans, I really appreciate that you wrote this awesome code in Pytorch. 
I tried to run this code on my conda environment (Pytorch 1.0.0 installed), got this error:

**(jmpark_py36) rit@rit:/media/rit/HDD/pdm/Pointnet2_PyTorch/build$ make
Scanning dependencies of target pointnet2_ext
[ 20%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/pointnet2/utils/csrc/cuda_compile_1_generated_ball_query_gpu.cu.o
[ 40%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/pointnet2/utils/csrc/cuda_compile_1_generated_group_points_gpu.cu.o
[ 60%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/pointnet2/utils/csrc/cuda_compile_1_generated_interpolate_gpu.cu.o
[ 80%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/pointnet2/utils/csrc/cuda_compile_1_generated_sampling_gpu.cu.o
[100%] Generating ../pointnet2/utils/_ext/pointnet2/_pointnet2.so
Traceback (most recent call last):
  File "/media/rit/HDD/pdm/Pointnet2_PyTorch/pointnet2/utils/build_ffi.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "/home/rit/anaconda3/envs/jmpark_py36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
CMakeFiles/pointnet2_ext.dir/build.make:67: recipe for target '../pointnet2/utils/_ext/pointnet2/_pointnet2.so' failed
make[2]: *** [../pointnet2/utils/_ext/pointnet2/_pointnet2.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pointnet2_ext.dir/all' failed
make[1]: *** [CMakeFiles/pointnet2_ext.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2**

I think this is because of the version mismatch. Can you provide me any suggestions?
Thank you!

Regards,

**Comment by erikwijmans** [comment]
Looks like the old way of doing pytorch extensions has been official deprecated in 1.0.  Changing this repo to use the newer method has been on the todo list for a while now, and it looks like it's time to bump the priority of that up.

This repo works/builds fine on `0.4.*`, so feel free to use any of those for now.

**Comment by chickenbestlover** [comment]
Thank you for your kind answer. Sadly, I have a 2080ti gpu that only supports version 1.0 of pytorch.
I tried to fix the ffi part myself, but it's too difficult. Therefore I am really looking forward to the update of this repo. Thank you so much!

**Comment by erikwijmans** [comment]
Give the pytorch-1.0.0 branch a try: https://github.com/erikwijmans/Pointnet2_PyTorch/tree/pytorch-1.0.0

It's a reasonably big change, so I want to sit on it a little before before merging into master.

**Comment by ZhangYuef** [comment]
It does not work for me on PyTorch `0.4.0`.

**Comment by erikwijmans** [comment]
What doesn’t work? What’s the error message?

**Comment by momo1986** [comment]
Similar issue in pytorch1.0
