### ISSUE TITLE
Calculation of mIoU for the segmentation task

### ISSUE THREAD

**Issue by h982639009** [erikwijmans/Pointnet2_PyTorch#15]
Thanks for your great efforts for the elegant implementation.  I wonder how to calculate the mIoU for the segmentation task. Could you give some examples in your implementation?

**Comment by erikwijmans** [comment]
The official codebase has IoU implemented for the part segmentation task: https://github.com/charlesq34/pointnet2/blob/master/part_seg/evaluate.py, I’d start there.
