### ISSUE TITLE
Unauthenticated git no longer supported

### ISSUE THREAD

**Issue by khmariem** [erikwijmans/Pointnet2_PyTorch#168]
The following command is no longer functional:
`pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"`

https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by iliiliiliili** [comment]
Replace `git://github.com` to `https://github.com` to make it work
