### ISSUE TITLE
Failed to build pointnet2_ops

### ISSUE THREAD

**Issue by kingchou007** [erikwijmans/Pointnet2_PyTorch#183]
Issue: Building PointNet++ with PyTorch 2.0.0+cu118 on Ubuntu 20.04

Environment:
- OS: Ubuntu 20.04
- CUDA: 11.8
- PyTorch: 2.0.0+cu118
- Python: 3.8

Error:
file or directory
          6 | #include "sampling_gpu.h"
            |          ^~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2_ops
  Running setup.py clean for pointnet2_ops
Failed to build pointnet2_ops
ERROR: Could not build wheels for pointnet2_ops, which is required to install pyproject.toml-based projects

**Comment by kingchou007** [comment]
I figure it out.

**Comment by Crescent-cc** [comment]
I face the same poblem ,could you tell me how to solve?
