### ISSUE TITLE
Error in building CUDA kernel

### ISSUE THREAD

**Issue by Na-Z** [erikwijmans/Pointnet2_PyTorch#2]
I can not successfully build '_pointnet2.so'. I encountered the following error:
==========================================================================
Scanning dependencies of target pointnet2_ext
[ 20%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_ball_query_gpu.cu.o
[ 40%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_interpolate_gpu.cu.o
[ 60%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_group_points_gpu.cu.o
[ 80%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/utils/csrc/cuda_compile_generated_sampling_gpu.cu.o
[100%] Generating ../utils/_ext/pointnet2/_pointnet2.so
usage: build_ffi.py [-h] [--build | --clean]
build_ffi.py: error: unrecognized arguments: --objs /*/build/CMakeFiles/cuda_compile.dir/utils/csrc/./cuda_compile_generated_ball_query_gpu.cu.o /*/build/CMakeFiles/cuda_compile.dir/utils/csrc/./cuda_compile_generated_interpolate_gpu.cu.o /*/build/CMakeFiles/cuda_compile.dir/utils/csrc/./cuda_compile_generated_group_points_gpu.cu.o /*/build/CMakeFiles/cuda_compile.dir/utils/csrc/./cuda_compile_generated_sampling_gpu.cu.o
CMakeFiles/pointnet2_ext.dir/build.make:67: recipe for target '../utils/_ext/pointnet2/_pointnet2.so' failed
make[2]: *** [../utils/_ext/pointnet2/_pointnet2.so] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pointnet2_ext.dir/all' failed
make[1]: *** [CMakeFiles/pointnet2_ext.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
==============================================================================

If I built  '_pointnet2.so' with running 'build_ffi.py', there has an error as follow:
==============================================================================
ImportError: /*/utils/_ext/pointnet2/_pointnet2.so: undefined symbol: three_interpolate_grad_kernel_wrapper
==============================================================================

**Comment by erikwijmans** [comment]
I am not sure what's going on, but here are some ideas:

1. I have not tested this build system on Windows
2. I use python3 for everything and python in the environment for this project is python3.

Can you run `make VERBOSE=1` and paste those results?

Running `build_ffi.py` by itself won't work.  It needs the compiled cuda kernels.
