### ISSUE TITLE
Multi-Gpu support

### ISSUE THREAD

**Issue by chenzhutian** [erikwijmans/Pointnet2_PyTorch#25]
It seems that the code currently hasn't enabled the multi-GPU via nn.DataParallel?
Do we need to manually enable the multi-GPU?

**Comment by erikwijmans** [comment]
I have not seen that error before.

**Comment by chenzhutian** [comment]
I have done some studies and it seems that this error is resutl from the h5py. https://github.com/h5py/h5py/issues/736

A possible walkaround is to read all the data into memory.
By doing so the error has not shown up yet.

**Comment by chenzhutian** [comment]
I think this issue can be closed.
