### ISSUE TITLE
Data type mismatched problem

### ISSUE THREAD

**Issue by SmallHedgehog** [erikwijmans/Pointnet2_PyTorch#29]
https://github.com/erikwijmans/Pointnet2_PyTorch/blob/eb2f0b7efec8aaad51fec2587eafa5b3a27873c9/pointnet2/utils/pointnet2_utils.py#L309

In class pointnet2.pointnet2_utils.QueryAndGroup's parameter of features(type: torch.Tensor with (B, C, N), but in pointnet2.pointnet2_modules.py xzy_feats is (B, N, C) in line 235

**Comment by erikwijmans** [comment]
The section in `pointnet2_modules.py` after `if __name__ == "__main__":` isn't maintained, intended to be used, nor indicative of how to use this code.  It is there as it can be useful for deep debugging.  I should probably move it to somewhere else however.

Please see the models definitions in `pointnet2/models` and the training scripts in `pointnet2/train` for maintained examples of using this repo.
