### ISSUE TITLE
Why the initial value of `bn_momentum` is 0.9?

### ISSUE THREAD

**Issue by chenzhutian** [erikwijmans/Pointnet2_PyTorch#30]
Hi I have a silly question.
According to https://github.com/charlesq34/pointnet2/blob/master/scannet/train.py#L57, the initial value of `BN_DECAY` should be 0.5.

In the meantime, the `0.9` for momentum is used for `momentum` optimizer. (https://github.com/charlesq34/pointnet2/blob/master/scannet/train.py#L30)

So I wonder does the 0.9 `bn_momentum` comes from the original implementation?
https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/train/train_sem_seg.py#L44

**Comment by erikwijmans** [comment]
I’m not sure. The official  semseg code didn’t come until long after I had implemented this, so looks like I made 0.9 the default for semseg for some reason. Should change that to 0.5.

**Comment by chenzhutian** [comment]
It seems that the implementation of `bn_lbmd` should be `bn_lbmd = lambda it: min(1 - cfg.BN['INIT_DECAY'] * cfg.BN['DECAY_RATE']**(int(it * cfg.BATCH_SIZE / cfg.BN['DECAY_STEP'])), cfg.BN['DECAY_CLIP'])`.

I am not sure. will study further and make a conclusion.
I have tried my own task on the origianal implementation with a good result but got a worse  performance on your code. Therefore I am trying to investigate the details.
