### ISSUE TITLE
error when build _ext module

### ISSUE THREAD

**Issue by bigsheep2018** [erikwijmans/Pointnet2_PyTorch#33]
Hello,
Thanks for updating the pytorch 1.0 version.
My environment is:
python 2.7, pytorch 1.0, Ubuntu 16.04, Cuda 9.0.176, cudnn 7.1.3, gcc 5.5, Nvidia GPU driver: 390.87

I got following errors when run 'python setup.py build_ext --inplace'

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9231): error: argument of type "const void *" is incompatible with parameter of type "const float *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9244): error: argument of type "const void *" is incompatible with parameter of type "const double *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9255): error: argument of type "const void *" is incompatible with parameter of type "const double *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9268): error: argument of type "const void *" is incompatible with parameter of type "const float *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9279): error: argument of type "const void *" is incompatible with parameter of type "const float *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9292): error: argument of type "const void *" is incompatible with parameter of type "const double *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9303): error: argument of type "const void *" is incompatible with parameter of type "const double *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9316): error: argument of type "const void *" is incompatible with parameter of type "const int *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9401): error: argument of type "const void *" is incompatible with parameter of type "const long long *"
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9410): error: argument of type "void *" is incompatible with parameter of type "float *"
...

I am guessing it is caused by the gcc version or cuda version problem.
May I know your environment? or any suggestions?
Thanks in advance.

**Comment by erikwijmans** [comment]
This looks to be an error with your gcc install.  All those errors are in gcc headers.

The only difference between our systems is the nvidia driver version (which shouldn't matter) and the gcc version (I am using 5.4).  I also tried it with gcc 5.3.  I don't have 5.5 installed anywhere unfortunately.

**Comment by eriche2016** [comment]
@bigsheep2018  I have tried your approach, but it doe snot work, donot figure out
