### ISSUE TITLE
Visdom does not display anything

### ISSUE THREAD

**Issue by GuesmiAbd** [erikwijmans/Pointnet2_PyTorch#36]
Hello,
train_sem_seg.py work very well but visdom does not display anything.

Thanks in advance,
Raouf

**Comment by erikwijmans** [comment]
It works for me.

Are there any errors from visdom?  Are you passing the `--visdom` flag and the correct port?

**Comment by GuesmiAbd** [comment]
Thank you for your response!
I solved the problem.
