### ISSUE TITLE
Inconsistency description in _PointnetSAModuleBase

### ISSUE THREAD

**Issue by QhelDIV** [erikwijmans/Pointnet2_PyTorch#39]
In pointnet2.utils.pointnet2_modules.py
The method forward in class _PointnetSAModuleBase has problematic description:
        
Returns
        -------
        new_xyz : torch.Tensor
            (B, npoint, 3) tensor of the new features' xyz
        new_features : torch.Tensor
            (B, npoint, \sum_k(mlps[k][-1])) tensor of the new_features descriptors
        """
But in the end new_features has the shape of (B, \sum_k(mlps[k][-1]), npoint)
This may introduce confusion, perhaps it is better to return in the form of (B, npoint, \sum_k(mlps[k][-1]))

**Comment by erikwijmans** [comment]
Looks like I need to update that docstring. It makes sense to keep features in (B, C, N) format as pytorch requires.
