### ISSUE TITLE
Compilation error CUDA can't found

### ISSUE THREAD

**Issue by spk921** [erikwijmans/Pointnet2_PyTorch#46]
I did symbolic linke /usr/local/cuda to /usr/loca/cuda-9.0 
Other application which use CUDA works fine and also exported CUDA_HOME. 
And got below error which indicate can't find CUDA. 

(py36) spk921@spk ~/git/Pointnet2_PyTorch [master*]$ python setup.py build_ext
running build_ext
building 'pointnet2._ext' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -I/usr/include/python3.6m -I/home/spk921/pyenv/py36/include/python3.6m -c pointnet2/_ext-src/src/bindings.cpp -o build/temp.linux-x86_64-3.6/pointnet2/_ext-src/src/bindings.o -O2 -Ipointnet2/_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:/include -I/usr/include/python3.6m -I/home/spk921/pyenv/py36/include/python3.6m -c pointnet2/_ext-src/src/interpolate.cpp -o build/temp.linux-x86_64-3.6/pointnet2/_ext-src/src/interpolate.o -O2 -Ipointnet2/_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
In file included from /home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAContext.h:5:0,
                 from pointnet2/_ext-src/include/utils.h:2,
                 from pointnet2/_ext-src/src/interpolate.cpp:2:
/home/spk921/pyenv/py36/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by spk921** [comment]
Figured it out.

**Comment by hillaric** [comment]
I met the same question, how did you solve it, thanks for your help

**Comment by shohinm** [comment]
How was this issue solved?

**Comment by akeaveny** [comment]
I'm also facing the same issue

**Comment by shohinm** [comment]
> I'm also facing the same issue

My issue was the cuda was not installed (I thought it was).

**Comment by SaiAakash** [comment]
> Figured it out.

Can you please let us know how you resolved this error ?
