### ISSUE TITLE
Why GatherOperation needs a backward method?

### ISSUE THREAD

**Issue by usherbob** [erikwijmans/Pointnet2_PyTorch#53]
Hello, Erik. Thanks for sharing your pytorch implementation of Pointnet2.  Actually, I want to know why we need a **backward method** for `GatherOperation` in `./utils/pointnet2_utils.py`. I believe there is no gradient in gather_pointt function, and do we really need `gather_point_grad` function?
```
class GatherOperation(Function):
    @staticmethod
    def forward(ctx, features, idx):
        # type: (Any, torch.Tensor, torch.Tensor) -> torch.Tensor
        r"""
        Parameters
        ----------
        features : torch.Tensor
            (B, C, N) tensor
        idx : torch.Tensor
            (B, npoint) tensor of the features to gather
        Returns
        -------
        torch.Tensor
            (B, C, npoint) tensor
        """

        _, C, N = features.size()

        ctx.for_backwards = (idx, C, N)

        return _ext.gather_points(features, idx)

    @staticmethod
    def backward(ctx, grad_out):
        idx, C, N = ctx.for_backwards

        grad_features = _ext.gather_points_grad(grad_out.contiguous(), idx, N)
        return grad_features, None
```

**Comment by erikwijmans** [comment]
If I recall correctly, it isn't needed at all for PointNet++ (i.e. that code path is never used), but it is simple enough to include, so I did, incase someone needs it.

**Comment by usherbob** [comment]
Thanks for your reply. 
But if we did not need backward, should we set backward method to `None`, like in `furthest sampling`?
```
class FurthestPointSampling(Function):
    @staticmethod
    def forward(ctx, xyz, npoint):
        # type: (Any, torch.Tensor, int) -> torch.Tensor
        r"""
        Uses iterative furthest point sampling to select a set of npoint features that have the largest
        minimum distance
        Parameters
        ----------
        xyz : torch.Tensor
            (B, N, 3) tensor where N > npoint
        npoint : int32
            number of features in the sampled set
        Returns
        -------
        torch.Tensor
            (B, npoint) tensor containing the set
        """
        return _ext.furthest_point_sampling(xyz, npoint)

    @staticmethod
    def backward(xyz, a=None):
        return None, None


furthest_point_sample = FurthestPointSampling.apply
```
[charlesq34/pointnet2](https://github.com/charlesq34/pointnet2) also included the graduate function for `gather point` in [sampling operation](https://github.com/charlesq34/pointnet2/blob/master/tf_ops/sampling/tf_sampling.py). 
So I wonder if there is a reason.

**Comment by erikwijmans** [comment]
The gradient for furthest point sampling is well defined for either input, that is why it returns None for both inputs.

**Comment by usherbob** [comment]
I get it. If I am right. I believe `GatherOpearion` needs a backward op to make sure **gradient** can be passed through in backward prop, just like **max pooling** needs a backward op.

**Comment by erikwijmans** [comment]
Yep!
