### ISSUE TITLE
number of points (xyz) is varying

### ISSUE THREAD

**Issue by sheshappanavar** [erikwijmans/Pointnet2_PyTorch#58]
If I do print(xyz.shape) inside the forward function of class QueryAndGroup in file pointnet2_utils.py I find the number of points varying.

I am using num_points as 1024. However, when I print I see it varying.

**Comment by erikwijmans** [comment]
Can you provide a minimal reproduction script?

**Comment by sheshappanavar** [comment]
1. Open file pointnet2/utils/pointnet2_utils.py
2. Insert print(xyz.shape) at line number 318 and save the file
3.  Open pointnet2/train/train_cls.py file and change num_points from 4096 to 1024 on line number 36 and save the file.
4. Now run python -m pointnet2.train.train_cls

Run 1: During training, it picked 912 points and while testing it picked 1109 points
Run 2: During training, it picked 1088 points and while testing it picked 990 points

**Comment by erikwijmans** [comment]
That's due to this: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/data/ModelNet40Loader.py#L89

I was playing around with varying the number of points during training to see how that effected with things and I guess that made its over here also!  I'll remove that
