### ISSUE TITLE
How do you visualize the extracted features?

### ISSUE THREAD

**Issue by longmalongma** [erikwijmans/Pointnet2_PyTorch#60]
How do you visualize the extracted features?Can you send me your code about visualization of extracted features?My email is that 1442342449@qq.com.Think you very much.

**Comment by erikwijmans** [comment]
I have never visualized extracted features and don't have any code to do so unfortunately :/

**Comment by longmalongma** [comment]
Think you




------------------ 原始邮件 ------------------
发件人: "Erik Wijmans"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 上午8:54
收件人: "erikwijmans/Pointnet2_PyTorch"<Pointnet2_PyTorch@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [erikwijmans/Pointnet2_PyTorch] How do you visualize theextracted features? (#60)




I have never visualized extracted features and don't have any code to do so unfortunately :/
