### ISSUE TITLE
Visdom does not work 

### ISSUE THREAD

**Issue by jiqirenzhifu** [erikwijmans/Pointnet2_PyTorch#67]
Hello, thank you for your great work. I have the following problems when I am running on the docker
`python -m pointnet2.train.train_sem_seg --visdom
`
But the system displays
`urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f38901e03c8>: Failed to establish a new connection: [Errno 111] Connection refused
`
Can you help me?

**Comment by lyf6** [comment]
i also met this problem, have u solved it?

**Comment by jiqirenzhifu** [comment]
> i also met this problem, have u solved it?

You should run 
`python -m visdom.server` 
before
`python -m pointnet2.train.train_sem_seg --visdom`
that is work

**Comment by lyf6** [comment]
@jiqirenzhifu thank u, i will try it
