### ISSUE TITLE
No 'sharedMLP'

### ISSUE THREAD

**Issue by CZ-Wu** [erikwijmans/Pointnet2_PyTorch#70]
I encounter the following  error:
`module 'pointnet2.utils.pytorch_utils' has no attribute 'SharedMLP'`

**Comment by VictorZuanazzi** [comment]
Same problem here! Any work arround it?

**Comment by erikwijmans** [comment]
Where does this error occur?  I haven't seen it.

**Comment by VictorZuanazzi** [comment]
At least for me, it was a problem with the folder structure. The original folder structure (after cloning the etw_pytorch_utils git) was `Pointnet2_PyTorch/etw_pytorch_utils/etw_pytorch_utils/*`, I just moved everything one level up to `Pointnet2_PyTorch/etw_pytorch_utils/*` and it started working.

Maybe I did something wrong, but 'pip install -f requirements.txt' did not install etw_pytorch_utils, so I had to clone it manually.
