### ISSUE TITLE
Error when running setup.py

### ISSUE THREAD

**Issue by asd40708** [erikwijmans/Pointnet2_PyTorch#72]
Hi,

I have some problem when I run python3 setup.py build_ext --inplace.
Here is the message shown:
running build_ext
building 'pointnet2._ext' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/lib/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/THC -I:/usr/local/cuda/include -I/usr/include/python3.6m -c /home/normanchang/Pointnet2_PyTorch/pointnet2/_ext-src/src/interpolate.cpp -o build/temp.linux-x86_64-3.6/home/normanchang/Pointnet2_PyTorch/pointnet2/_ext-src/src/interpolate.o -O2 -I/home/normanchang/Pointnet2_PyTorch/pointnet2/_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
In file included from /usr/local/lib/python3.6/dist-packages/torch/lib/include/ATen/cuda/cuda_runtime_api.h:139,
                 from /usr/local/lib/python3.6/dist-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/lib/include/ATen/cuda/CUDAContext.h:5,
                 from /home/normanchang/Pointnet2_PyTorch/pointnet2/_ext-src/include/utils.h:2,
                 from /home/normanchang/Pointnet2_PyTorch/pointnet2/_ext-src/src/interpolate.cpp:2:
/usr/local/lib/python3.6/dist-packages/torch/lib/include/ATen/cuda/builtin_types.h:56:10: fatal error: /usr/local/lib/python3.6/dist-packages/torch/lib/include/ATen/cuda/device_types.h: Too many levels of symbolic links
 #include "device_types.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I used ssh to connect to a workstation and ran the command. 
The environment of the workstation is as follow:
Ubuntu 18.04
Python 3.6.8
CUDA 10.0
(If you need more information, please tell me.)

I can't figure out what's the real problem to this error. 
Hope that you can give me some solution to it.
Thanks.

**Comment by erikwijmans** [comment]
This appears to be an issue with either your pytorch install or a bug in pytorch.

**Comment by asd40708** [comment]
Thanks for the reply. I have solved it. The link to the cuda file of our workstation somehow didn't work well. I re-installed pytorch in local to solve it.
