### ISSUE TITLE
CUDA kernel failed : invalid device function

### ISSUE THREAD

**Issue by fuweifu-vtoo** [erikwijmans/Pointnet2_PyTorch#74]
I ran train_cls.py, then  encounter this error:

the error is:
CUDA kernel failed : invalid device function
void furthest_point_sampling_kernel_wrapper(int b, int n, int m,
                                            const float *dataset, float *temp,
                                            int *idxs) in /Pointnet2_PyTorch/pointnet2/_ext-src/src/sampling_gpu.cu

Do you know why?

**Comment by GuMingDiaoYu** [comment]
I had the same problem and finally solved it. This may be caused by the version of Pytorch, try to recreate a virtual environment and follow the installment guide.

**Comment by Frostinassiky** [comment]
@YimingCuiCuiCui 's solution works in my case. I met the same error with **Python 3.7.6**. 
Then a create a new conda environment with **Python 3.6.10** and the code is running successfully!

**Comment by w5688414** [comment]
I meet the same error:

```
Validation sanity check: 0it [00:00, ?it/s]CUDA kernel failed : invalid device function
void furthest_point_sampling_kernel_wrapper(int, int, int, const float*, float*, int*) at L:228 in pointnet2_ops/_ext-src/src/sampling_gpu.cu
[1]    28932 segmentation fault (core dumped)  python pointnet2/train.py task=cls

```
my python version is 3.6.4

**Comment by aligholami** [comment]
did you manage to solve it? isn't it because of inadequate shared memory (probably caused by high batch size)?

**Comment by HansRen1024** [comment]
Here is the best solution:

https://github.com/mkt1412/GraspGPT_public/issues/8
