### ISSUE TITLE
weird kernel dispatch for gradient of 3-interpolate

### ISSUE THREAD

**Issue by timetomakesense** [erikwijmans/Pointnet2_PyTorch#77]
Hi 

From Votenet repository, which uses this implementation of pointnet2, I notice an issue about three_interpolate_grad_kernel_wrapper; 
https://github.com/facebookresearch/votenet/issues/36#issue-508854259

It says:'It appears that gradient kernel was never actually used cuz here it's dispatching the same kernel as in forward'

May I ask you implemented intentionally or is it a bug?

**Comment by erikwijmans** [comment]
Definitely a bug!  Interesting that it doesn't seem to matter for the performance of PointNet++ or votenet as that has been there for a _long_ time.  Deep learning is weird!
