### ISSUE TITLE
Error: module 'pytorch_utils' has no attribute 'SharedMLP'

### ISSUE THREAD

**Issue by minhncsocial** [erikwijmans/Pointnet2_PyTorch#8]
Hi Erik,
Thank you for sharing pointnet source.
When I run your code I get error:

`Traceback (most recent call last):
  File "/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/train_cls.py", line 118, in <module>
    model = Pointnet(input_channels=0, num_classes=40, use_xyz=True)
  File "/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/pointnet2_msg_cls.py", line 62, in __init__
    use_xyz=use_xyz
  File "/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/../utils/pointnet2_modules.py", line 107, in __init__
    self.mlps.append(pt_utils.SharedMLP(mlp_spec, bn=bn))
AttributeError: module 'pytorch_utils' has no attribute 'SharedMLP'`

I can not find out pytorch_utils module.
Could you share me that file?

Thank you very much.
Minhh

**Comment by erikwijmans** [comment]
`pytorch_utils` is in this repo: https://github.com/erikwijmans/etw_pytorch_utils.  That repo is already added as a git-submodule.  Looks like I didn't include the recommendation to clone with `--recursive` in this readme for this repo.  You can checkout the submodule with `git submodule update --init --recursive`.

**Comment by minhncsocial** [comment]
Thank Erik very much.
I got your file and above issue was solved.

But I got another error when I run pytorch_utils. Have you ever met this error?
`/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/../utils/pytorch_utils/pytorch_utils.py:104: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init(conv_unit.weight)
/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/../utils/pytorch_utils/pytorch_utils.py:53: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(self[0].weight, 1.0)
/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/../utils/pytorch_utils/pytorch_utils.py:54: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(self[0].bias, 0)
/home/minhnc-lab/WORKSPACES/Python/GRASP_DETECTION/PointNet/Pointnet2_PyTorch/models/../utils/pytorch_utils/pytorch_utils.py:252: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(fc.bias, 0)
epochs:   0%|          | 0/200 [00:00<?, ?it/s]
train:   0%|          | 0/615 [00:00<?, ?it/s]CUDA kernel failed : CUDA driver version is insufficient for CUDA runtime version
`

**Comment by minhncsocial** [comment]
Thank you for your kind reply. 
Because my environment is able to run pointnet pytorch v1. So maybe your environment is a little special. 
Could you mind share me your .yml environment file?

**Comment by minhncsocial** [comment]
Haha. Thank you. I already install pytorch 4.0.
Could you export your conda environment?
