### ISSUE TITLE
Memory Usage 

### ISSUE THREAD

**Issue by shersoni610** [erikwijmans/Pointnet2_PyTorch#80]
hello,

I am trying to run the demo, but it seems 6GB card is not sufficient. I get the following message:

training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 5.94 GiB total capacity; 4.87 GiB already allocated; 219.56 MiB free; 118.69 MiB cached)

Is there a way to reduce the memory requirement?

**Comment by erikwijmans** [comment]
You can reduce the batch size and/or number of points in the input point clouds.
