### ISSUE TITLE
Error when building ext module

### ISSUE THREAD

**Issue by lianghouhao** [erikwijmans/Pointnet2_PyTorch#81]
Hello, really appreciate your work.  I followed your instructions on setup steps. But I met the error: ImportError: Could not import _ext module.

I actually 

```
_run python pointnet2/setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-3.5/pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so -> pointnet2_
```

The error:
```

_Traceback (most recent call last):
  File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_utils.py", line 26, in <module>
    import pointnet2._ext as _ext
ImportError: dynamic module does not define module export function (PyInit__ext)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/votenet.py", line 19, in <module>
    from backbone_module import Pointnet2Backbone
  File "/home/houhao/paper_implementation/votenet/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_utils.py", line 30, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

```
Actually I wanna use votenet and it needs pointnet setup. Here is the log i run the pointnet setup in votenet.

```
running install
running bdist_egg
running egg_info
writing dependency_links to pointnet2.egg-info/dependency_links.txt
writing top-level names to pointnet2.egg-info/top_level.txt
writing pointnet2.egg-info/PKG-INFO
reading manifest file 'pointnet2.egg-info/SOURCES.txt'
writing manifest file 'pointnet2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pointnet2
copying build/lib.linux-x86_64-3.5/pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pointnet2
creating stub loader for pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pointnet2/_ext.py to _ext.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pointnet2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pointnet2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pointnet2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pointnet2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pointnet2.__pycache__._ext.cpython-35: module references __file__
creating 'dist/pointnet2-0.0.0-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pointnet2-0.0.0-py3.5-linux-x86_64.egg
creating /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages/pointnet2-0.0.0-py3.5-linux-x86_64.egg
Extracting pointnet2-0.0.0-py3.5-linux-x86_64.egg to /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages
Adding pointnet2 0.0.0 to easy-install.pth file

Installed /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages/pointnet2-0.0.0-py3.5-linux-x86_64.egg
Processing dependencies for pointnet2==0.0.0
Finished processing dependencies for pointnet2==0.0.0
```
Can you help me how to fix this error? really appreciate your time.

**Comment by erikwijmans** [comment]
Please follow the build instructions at on the votenet repo (https://github.com/facebookresearch/votenet#installation) and/or open an issue there.

**Comment by Violetit** [comment]
> Hello, really appreciate your work. I followed your instructions on setup steps. But I met the error: ImportError: Could not import _ext module.
> 
> I actually
> 
> ```
> _run python pointnet2/setup.py build_ext --inplace
> running build_ext
> copying build/lib.linux-x86_64-3.5/pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so -> pointnet2_
> ```
> 
> The error:
> 
> ```
> 
> _Traceback (most recent call last):
>   File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_utils.py", line 26, in <module>
>     import pointnet2._ext as _ext
> ImportError: dynamic module does not define module export function (PyInit__ext)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "models/votenet.py", line 19, in <module>
>     from backbone_module import Pointnet2Backbone
>   File "/home/houhao/paper_implementation/votenet/models/backbone_module.py", line 19, in <module>
>     from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
>   File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_modules.py", line 21, in <module>
>     import pointnet2_utils
>   File "/home/houhao/paper_implementation/votenet/pointnet2/pointnet2_utils.py", line 30, in <module>
>     "Could not import _ext module.\n"
> ImportError: Could not import _ext module.
> Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst
> ```
> 
> Actually I wanna use votenet and it needs pointnet setup. Here is the log i run the pointnet setup in votenet.
> 
> ```
> running install
> running bdist_egg
> running egg_info
> writing dependency_links to pointnet2.egg-info/dependency_links.txt
> writing top-level names to pointnet2.egg-info/top_level.txt
> writing pointnet2.egg-info/PKG-INFO
> reading manifest file 'pointnet2.egg-info/SOURCES.txt'
> writing manifest file 'pointnet2.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/pointnet2
> copying build/lib.linux-x86_64-3.5/pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pointnet2
> creating stub loader for pointnet2/_ext.cpython-35m-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/pointnet2/_ext.py to _ext.cpython-35.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying pointnet2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying pointnet2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying pointnet2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying pointnet2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> pointnet2.__pycache__._ext.cpython-35: module references __file__
> creating 'dist/pointnet2-0.0.0-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing pointnet2-0.0.0-py3.5-linux-x86_64.egg
> creating /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages/pointnet2-0.0.0-py3.5-linux-x86_64.egg
> Extracting pointnet2-0.0.0-py3.5-linux-x86_64.egg to /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages
> Adding pointnet2 0.0.0 to easy-install.pth file
> 
> Installed /home/houhao/anaconda3/envs/pytorch=1/lib/python3.5/site-packages/pointnet2-0.0.0-py3.5-linux-x86_64.egg
> Processing dependencies for pointnet2==0.0.0
> Finished processing dependencies for pointnet2==0.0.0
> ```
> 
> Can you help me how to fix this error? really appreciate your time.

Hi, @houhaol 
I miss this error too, did you solve it?
