### ISSUE TITLE
Errors for num_classes = 1

### ISSUE THREAD

**Issue by tbarton16** [erikwijmans/Pointnet2_PyTorch#89]
`opt/conda/conda-bld/pytorch_1570710853631/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.`

RuntimeError: CUDA error: device-side assert triggered

I want to do a binary classifier on points.  My labels are all either 0 or 1 for each point.  Does anyone know how to fix this?

**Comment by erikwijmans** [comment]
If all of your labels are either 0 or 1, you have 2 classes, not 1.
