### ISSUE TITLE
isFloatingType

### ISSUE THREAD

**Issue by ShengyuH** [erikwijmans/Pointnet2_PyTorch#95]
hi, 

I use Pointnet2 as per-point embedding and plug-in to another network, then I got this error:

RuntimeError: Expected isFloatingType(grads[i].type().scalarType()) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

I have examined all the scalar types of weights, they are torch.float32, I believe this is due to PointNet2 embedding module as when I replace it with other backbones, I don't have any error. Are there anyone meeting the same error?

**Comment by join16** [comment]
I got a same problem, and now I think there was a problem in furthest_point_sample module.
And I solved it by detaching an input tensor of pointnet2_utils.furthest_point_sample.

Changing code like

pointnet2_utils.furthest_point_sample(xyz.detach(), N).

can solve this problem.

**Comment by erikwijmans** [comment]
Ah, looks like PyTorch has changed why they expect for non-differentiable outputs.  You now need to return a tensor of all-zeros instead of None and mark it as non-differentiable: https://pytorch.org/docs/stable/autograd.html#torch.autograd.function._ContextMethodMixin.mark_non_differentiable

**Comment by erikwijmans** [comment]
#102

**Comment by ShengyuH** [comment]
> I got a same problem, and now I think there was a problem in furthest_point_sample module.
> And I solved it by detaching an input tensor of pointnet2_utils.furthest_point_sample.
> 
> Changing code like
> 
> ```python
> pointnet2_utils.furthest_point_sample(xyz.detach(), N)
> ```
> 
> will solve this problem.

Thanks!
