### ISSUE TITLE
Multi-GPU issue

### ISSUE THREAD

**Issue by WhynotBicycle** [erikwijmans/Pointnet2_PyTorch#96]
Hi Erik,

On multi-GPU machines, the BallQuery() will always return zeros when I set the device as 'cuda:1'. If the device is 'cuda:0', then life is easy. Could I ask how to solve it? 

Cheers,
Shidi

**Comment by erikwijmans** [comment]
You likely aren't calling `torch.cuda.set_device` to change which device the CUDA kernels get launched on -- pytorch does some magic to not require that call for their kernels, but I have no idea how they do that :)
