### ISSUE TITLE
About the processed data set used in this implementation

### ISSUE THREAD

**Issue by CodeLHY** [erikwijmans/Pointnet2_PyTorch#98]
hi @erikwijmans ,
I'm sorry to bother you again,
I noticed that you use the processed data set(the first three dim is XYZ, and the rest are called "feature" in your code) instead of the origin ModelNet40.  How can I know what the process of the original data set is, or in other words how to calculate the "feature"?

**Comment by erikwijmans** [comment]
The data comes from XYZ+normals in the official TF implementation here: https://github.com/charlesq34/pointnet2#shape-classification
