### ISSUE TITLE
[Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by MoyGcc** [erikwijmans/Pointnet2_PyTorch#99]
Hello Erik,

I had the following issue when I ran the "python pointnet2/train.py task=cls". All the setup.py were installed completely and could you have a look on that?

/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py:13: UserWarning: data_loader decorator deprecated in 0.7.0. Will remove 0.9.0
  warnings.warn(w)
Traceback (most recent call last):
  File "pointnet2/train.py", line 33, in <module>
    main()
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "pointnet2/train.py", line 19, in main
    verbose=True,
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 93, in __init__
    os.makedirs(self.dirpath, exist_ok=True)
  File "/cluster/home/cheguo/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by marcelschilling** [comment]
Had the same problem, fixed it by changing the filepath in the checkpoint callback. However, afterwards i have other error (with 
configure_optimizers fcn -> 
raise ValueError(f'Input {scheduler} to lr schedulers '
ValueError: Input <pointnet2.models.pointnet2_ssg_cls.BNMomentumScheduler object at 0x7fea1eeb0e80> to lr schedulers is a invalid input
and with the logging ->
and TypeError: parameter: hparam_dict should be a dictionary, nothing logged. )
Have you solutions for fixing it (using CUDA 10.1, python 3.6 and the PyTorch 1.4.0)?

**Comment by MoyGcc** [comment]
> Had the same problem, fixed it by changing the filepath in the checkpoint callback. However, afterwards i have other error (with
> configure_optimizers fcn ->
> raise ValueError(f'Input {scheduler} to lr schedulers '
> ValueError: Input <pointnet2.models.pointnet2_ssg_cls.BNMomentumScheduler object at 0x7fea1eeb0e80> to lr schedulers is a invalid input
> and with the logging ->
> and TypeError: parameter: hparam_dict should be a dictionary, nothing logged. )
> Have you solutions for fixing it (using CUDA 10.1, python 3.6 and the PyTorch 1.4.0)?

I met the same problem as you after I fixed the file path. And the environment is almost the same except I have python 3.7, but I don't think it's a big deal. And now we got no idea in terms of the BNMomentumScheduler

**Comment by marcelschilling** [comment]
It seems to me, that the hyperparam error arises because the args are of type OmegaConf and not of type dict. However, simple dict casting won't work. Unfortunately, I have no idea due to the BNMomentumScheduler problem.
